export const IPC_CHANNELS = {
  TAB_CREATE: 'tab:create',
  TAB_CLOSE: 'tab:close',
  TAB_SELECT: 'tab:select',
  TAB_NAVIGATE: 'tab:navigate',
  TAB_GO_BACK: 'tab:go-back',
  TAB_GO_FORWARD: 'tab:go-forward',
  TAB_RELOAD: 'tab:reload',
  TAB_STOP: 'tab:stop',
  TAB_URL_CHANGED: 'tab:url-changed',
  TAB_TITLE_CHANGED: 'tab:title-changed',
  TAB_LOADING_CHANGED: 'tab:loading-changed',
  TAB_FAVICON_CHANGED: 'tab:favicon-changed',
  WEBVIEW_READY: 'webview:ready',
  WINDOW_MINIMIZE: 'window:minimize',
  WINDOW_MAXIMIZE: 'window:maximize',
  WINDOW_CLOSE: 'window:close',
  NAVIGATE_TO_URL: 'navigate:to-url',
  BANG_RESOLVE: 'bang:resolve',
} as const;
